<<<<<<< HEAD
version: "3"

services:
  server:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./data:/data
      - ./server.properties:/data/server.properties
    environment:
      EULA: "TRUE"
      VERSION: 1.14.3
      MEMORY: 4G
=======
version: "2.3"

services:
  python:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: docker_template_python
    env_file:
      - ./.env
    ports:
      - "8888:8888"
    runtime: nvidia
    tty: true
    volumes:
      - ./source:/usr/src/source
    working_dir: /usr/src/source
>>>>>>> b075047... Initial commit
